version: '0.1.0'
services:

  influxdb:
    image: influxdb
    #restart: always
    volumes:
        - /data:/var/lib/influxdb 
          #    ports: 
          #- 8086:8086
    container_name: influxdb

  telegraf:
    image: telegraf
    #restart: always
    volumes:
        - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    container_name: telegraf
