version: '0.1.0'
services:

  influxdb:
    image: influxdb:latest
    restart: always
    volumes:
        - /data/influxdb:/var/lib/influxdb 
    ports: 
        - 8086:8086
    container_name: influxdb

  telegraf:
    image: telegraf:latest
    restart: always
    links:
        - influxdb:influxdb
    volumes:
        - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    container_name: telegraf
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
        - 3000:3000
    links:
        - influxdb
    volumes:
        - /data/grafana:/var/lib/grafana
        - grafana/grafana
